# Generated by Django 4.1.3 on 2022-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0002_familiares_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='fecha',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='dni',
            field=models.CharField(default='', max_length=8),
        ),
    ]
